### ISSUE TITLE
(유건욱 김주형 정의재) 겜프프로젝트 과정평가용(방문기록)

### ISSUE THREAD

**Issue by GGMinwok** [yugunuk0716/UnityLab#1]
5/26 깃허브 접속 가능여부 확인함

**Comment by GGMinwok** [comment]
오늘 기록할 때 지금까지 한 것(오늘 이전꺼~), 6/8 오늘 1-3교시에 한 것 구분해서 과정 기록 해주기!

**Comment by kungsae** [comment]
문제를 맞췄을때 해당 문제에 대한 플레이 화면 띄우기 기본 시스템 완성 + 1스테이지 인게임 구현 완성

**Comment by yugunuk0716** [comment]
1교시: 코인 저장 및 불러오기, 스테이지 클리어시 코인 획득 시스템
2교시: 힌트 UI 구조 짜기
3교시: 힌트 UI 코드 짜기

**Comment by GGMinwok** [comment]
6/15 기록 확인함.

**Comment by yugunuk0716** [comment]
1교시: 클리어시 먹은 코인을 바탕으로 아이템 구매 UI 제작
2교시: 아이템 구매 UI를 통하여 힌트 아이템 얻기
3교시: 힌트 시스템 개발(단어에 마우스 올리면 설명이 뜹니다)

**Comment by kungsae** [comment]
기존 문제를 맞췄을 때 실제 구동하는 화면을 ui에서 카메라 두개로 띄우는 방식을 바꿈
기존 ui로 만들어놨던 스테이지들 변경

**Comment by GGMinwok** [comment]
6/22 이전주 작업확인
유건욱 확인/정의재 확인

**Comment by kungsae** [comment]
인게임에서 총알이 발사되지 않는 버그 수정
인게임에서 총알이 충돌 체크가 되지 않는 버그 수정
인게임에서 적이 죽지 않는 버그 수정
인게임 ui 비정상적으로 큰 크기로 출력되는 버그 수정

**Comment by yugunuk0716** [comment]
1교시: Title UI 버그 수정 및 인게임 UI 위치 수정
2교시: 인게임 내에서 버튼을 누르면 답안이 있는 상자와 문제 상자가 아래로 내려가고 코드 부분의 크기가 커지는 기능 구현
3교시: 2교시에 만들었던 기능을 Dotween을 사용하여 좀 더 자연스럽고 부드럽게 수정

**Comment by GGMinwok** [comment]
6/30 유건욱, 정의재 과정 확인
고생했어요~^^
마지막 확인완료
작업과정 기록 남겨두세요. 
(2022년 동안 삭제 금지)
